version: '3.7'
services:
  postgres:
    build: ./data
    environment:
      TZ: Australia/Melbourne
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
